# Generated by Django 3.1.1 on 2020-09-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_post_asn'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_asn',
            name='LOCATION',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
